<?php
/**
 * @Author im.phien
 * @Date   Nov 24, 2024
 */

namespace App\Http\Controllers;

use App\Models\Approval;
use App\Services\ApprovalService;
use App\Transformers\Approval\ApprovalCollection;
use App\Transformers\Commons\ErrorResource;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use YaangVu\LaravelBase\Base\BaseController;
use OpenApi\Attributes as OA;

class ApprovalController extends BaseController
{
    public function __construct(private readonly Approval $approval, string $approvalService = ApprovalService::class)
    {
        parent::__construct($this->approval, $approvalService);
    }

    #[OA\Get(
        path: '/approvals',
        summary: 'Get approvals. ***DONE***',
        security: [['BearerAuth' => []]],
        tags: ['APPROVAL'],
        parameters: [
            new OA\Parameter(
                name:        'start_date',
                description: 'Start date',
                in:          'query',
                schema:      new OA\Schema(
                                 type: 'string',
                             ),
                example:     '13-08-2000'
            ),
            new OA\Parameter(
                name:        'end_date',
                description: 'End date',
                in:          'query',
                schema:      new OA\Schema(
                                 type: 'string',
                             ),
                example:     '13-08-2000'
            ),
            new OA\Parameter(
                name: 'type',
                description: 'Type',
                in:          'query',
                schema:      new OA\Schema(
                          type: 'integer',
                      ),
                example: '1',
            ),
            new OA\Parameter(
                name: 'status',
                description: 'Type',
                in:          'query',
                schema:      new OA\Schema(
                          type: 'integer',
                      ),
                example: '1',
            ),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Successful',
                content: new OA\JsonContent(ref: ApprovalCollection::class)
            ),
            new OA\Response(
                response: 400,
                description: 'End date invalid.',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 401,
                description: 'Unauthenticated',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 500,
                description: "Server error",
                content: new OA\JsonContent(ref: ErrorResource::class)
            )
        ]
    )]
    public function getAll(Request $request): JsonResponse
    {
        $result = ApprovalCollection::make($this->service->getAll($request));

        return response()->json($result);
    }

    public function store(Request $request): JsonResponse
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    public function update($id, Request $request): JsonResponse
    {
        return parent::update($id, $request); // TODO: Change the autogenerated stub
    }
}