<?php
/**
 * @Author im.phien
 * @Date   Nov 24, 2024
 */

namespace App\Http\Controllers;

use App\Http\Requests\Notification\CreateNotificationRequest;
use App\Models\Notification;
use App\Services\NotificationService;
use App\Transformers\Commons\ErrorResource;
use App\Transformers\Commons\TrvSuccessResource;
use App\Transformers\Notification\NotificationCollection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use YaangVu\LaravelBase\Base\BaseController;
use OpenApi\Attributes as OA;

class NotificationController extends BaseController
{
    public function __construct(private readonly Notification $notification, string $notificationService = NotificationService::class)
    {
        parent::__construct($this->notification, $notificationService);
    }

    #[OA\Get(
        path: '/notifications',
        summary: 'Get notifications. ***DONE***',
        security: [['BearerAuth' => []]],
        tags: ['RECRUITMENTS'],
        parameters: [
            new OA\Parameter(
                name:        'start_date',
                description: 'Start date',
                in:          'query',
                schema:      new OA\Schema(
                                 type: 'string',
                             ),
                example:     '13-08-2000'
            ),
            new OA\Parameter(
                name:        'end_date',
                description: 'End date',
                in:          'query',
                schema:      new OA\Schema(
                                 type: 'string',
                             ),
                example:     '13-08-2000'
            ),
            new OA\Parameter(
                name: 'position',
                description: 'Position',
                in:          'query',
                schema:      new OA\Schema(
                          type: 'string',
                      ),
                example: 'Developer',
            ),
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Successful',
                content: new OA\JsonContent(ref: NotificationCollection::class)
            ),
            new OA\Response(
                response: 400,
                description: 'End date invalid.',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 401,
                description: 'Unauthenticated',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 500,
                description: "Server error",
                content: new OA\JsonContent(ref: ErrorResource::class)
            )
        ]
    )]
    public function getAll(Request $request): JsonResponse
    {
        $result = NotificationCollection::make($this->service->getAll($request));

        return response()->json($result);
    }

    #[OA\Post(
        path: '/notifications',
        summary: 'Create notifications. ***DONE***',
        security: [['BearerAuth' => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                          ref: CreateNotificationRequest::class
                      )
        ),
        tags: ['NOTIFICATIONS'],
        responses: [
            new OA\Response(
                response: 200,
                description: 'Successful',
                content: new OA\JsonContent(ref: TrvSuccessResource::class)
            ),
            new OA\Response(
                response: 400,
                description: 'Start_date invalid.',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 401,
                description: 'Unauthenticated',
                content: new OA\JsonContent(ref: ErrorResource::class)
            ),
            new OA\Response(
                response: 500,
                description: "Server error",
                content: new OA\JsonContent(ref: ErrorResource::class)
            )
        ]
    )]
    public function store(Request $request): JsonResponse
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }
}