name: hrm_api_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: Pa55w0rd
          MYSQL_DATABASE: hrm
        ports:
          - 3306:3306
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
      
    - name: Build Docker image
      run: docker build . -f ./docker/php/Dockerfile -t laravel-image:latest

    - name: Run Container
      run: docker run --name laravel-container --network host -e DB_HOST=127.0.0.1 -e DB_DATABASE=hrm -e DB_USERNAME=root -e DB_PASSWORD=Pa55w0rd -d laravel-image:latest

    - name: Run install composer
      run: docker exec laravel-container composer install

    - name: Run migrate
      run: docker exec laravel-container php artisan migrate --env=testing
      
    - name: Generate key
      run: docker exec laravel-container php artisan key:generate
      
